services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: notdrive
      POSTGRES_PASSWORD: notdrive
      POSTGRES_DB: notdrive
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    profiles: ['pg']

  mailhog:
    image: mailhog/mailhog:latest
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  pgdata:
